name: API Endpoint Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 12 * * 1'  # weekly check

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"   # stable for FastAPI stack

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx

      - name: Run local API tests (TestClient)
        run: pytest -v v2_api/test_api_endpoints.py

      - name: Run live API tests (Render deployment)
        if: github.event_name == 'schedule'
        env:
          RUN_LIVE: true
        run: pytest -v v2_api/test_api_endpoints.py